title: Kerala IoT Challenge
email: amareshs2001@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This page is used to keep track of the experiments 
baseurl: "Kerala-IoT-Challenge" # the subpath of your site, e.g. /blog
url: "https://unknown-flyin-wayfarer-backup.github.io/Kerala-IoT-Challenge/" # the base hostname & protocol for your site, e.g. http://example.com
theme: jekyll-theme-architect
github:
  is_project_page: false
